name: bds
channels:
    - pytorch
dependencies:
    - python==3.7.6
    - pytorch==1.4
    - numpy
    - scikit-learn
    - pandas
    - pip
    - matplotlib
    - pip:
        - transformers==2.3.0
        - tqdm
